services:
    denizgelion_chartjs.navigation_listener:
        class: denizgelion\ContaoChartJsBundle\EventListener\NavigationListener
        arguments:
        - "@request_stack"
        - "@router"
        tags:
        - { name: contao.hook, hook: getUserNavigation }